version: "3"

services:
  bitcoindsim:
    build:
      context: contrib/images/bitcoindsim/
      dockerfile: ./Dockerfile
    image: babylonchain/bitcoindsim:latest
    platform: linux/amd64
    container_name: bitcoindsim
    environment:
      - ZMQ_SEQUENCE_PORT=29000
      - ZMQ_RAWBLOCK_PORT=29001
      - ZMQ_RAWTR_PORT=29002
      - RPC_PORT=18443
      - RPC_USER=rpcuser
      - RPC_PASS=rpcpass
      - WALLET_PASS=walletpass
      - WALLET_NAME=default
      - BTCSTAKER_WALLET_NAME=btcstaker
      - BTCSTAKER_WALLET_ADDR_COUNT=3
      - GENERATE_INTERVAL_SECS=10
    ports:
      - "18443:18443"
      - "29000-29002:29000-29002"
    volumes:
      - ../.testnets/bitcoin:/bitcoindsim/.bitcoin:Z
    networks:
      - phase-1

  staking-indexer:
    image: babylonchain/staking-indexer:latest
    container_name: staking-indexer
    environment:
      - CONFIG=/home/staking-indexer/.sid/sid.conf
    volumes:
      - ../.testnets/staking-indexer/data:/home/staking-indexer/.sid/data:Z
      - ../.testnets/staking-indexer/logs:/home/staking-indexer/.sid/logs:Z
      - ../.testnets/staking-indexer/sid.conf:/home/staking-indexer/.sid/sid.conf:Z
      - ../.testnets/global-params.json:/home/staking-indexer/.sid/global-params.json:Z
    depends_on:
      - rabbitmq
      - bitcoindsim
    entrypoint: ["/bin/sh", "-c", "/bin/sid start --start-height 1"]
    networks:
      - phase-1
    restart: unless-stopped

  staking-api-service:
    image: babylonchain/staking-api-service:latest
    container_name: staking-api-service
    ports:
      - "80:8090"
    environment:
      - CONFIG=/home/staking-api-service/config.yml
    volumes:
      - ../.testnets/global-params.json:/home/staking-api-service/global-params.json:Z
      - ../.testnets/staking-api-service/staking-api-service-config.yml:/home/staking-api-service/config.yml:Z
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - phase-1
    restart: unless-stopped

  staking-expiry-checker:
    image: babylonchain/staking-expiry-checker:latest
    container_name: staking-expiry-checker
    environment:
      - CONFIG=/home/staking-expiry-checker/config.yml
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ../.testnets/staking-expiry-checker/staking-expiry-checker-config.yml:/home/staking-expiry-checker/config.yml:Z
    networks:
      - phase-1
    restart: unless-stopped

  simple-staking:
    container_name: simple-staking
    image: babylonchain/simple-staking:latest
    environment:
      - APP_NEXT_PUBLIC_MEMPOOL_API=https://babylon.mempool.space
      - APP_NEXT_PUBLIC_API_URL=http://staking-api-service
    restart: always
    depends_on:
      - staking-api-service
    ports:
      - 3000:3000
    networks:
      - phase-1

  unbonding-pipeline:
    container_name: unbonding-pipeline
    image: babylonchain/cli-tools:latest
    restart: unless-stopped
    depends_on:
      - mongodb
      - bitcoindsim
    volumes:
      - ../.testnets/unbonding-pipeline/unbonding-pipeline-config.toml:/home/cli-tools/.tools/config.toml
    entrypoint: |
      /bin/sh -c "
      while true
      do
        cli-tools run-unbonding-pipeline --config /home/cli-tools/.tools/config.toml
        sleep 10
      done
      "
    networks:
      - phase-1

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../.testnets/mongo/init-mongo.sh:/init-mongo.sh:Z
    entrypoint: [ "/init-mongo.sh" ]
    networks:
      - phase-1

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "../.testnets/rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - phase-1

networks:
  phase-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/25
