server:
  host: 0.0.0.0
  port: 8090
  write-timeout: 60s
  read-timeout: 60s
  idle-timeout: 60s
  allowed-origins: [ "*" ]
aggregators:
  max-validator-participated-blocks: 1000
  max-validator-participated-epochs: 50
db:
  address: "mongodb://mongodb:27017"
  db-name: rpc-poller
stakerrpc:
  # API write operation to staker is only workarounds for dev/testnet testing purpose.
  # For local setup, we will replace this with *wiremock* to avoid writes to the devnet
  address: "localhost:15812" 
  network: "tcp"
metrics:
  host: 0.0.0.0
  port: 2112
