db:
  address: "mongodb://mongodb:27017"
  db-name: rpc-poller
stakerrpc:
  # API write operation to staker is only workarounds for dev/testnet testing purpose.
  # For local setup, we will replace this with *wiremock* to avoid writes to the devnet
  address: "localhost:15812" 
  network: "tcp"
babylon:
  rpc-addr: https://rpc.devnet.babylonchain.io:443
  timeout: 20s
poller:
  intervals:
    connected-chain-list: 1m
    connected-chains-info: 1m
    finalized-connected-chains-info: 1m
    connected-chain-headers: 1m
    raw-checkpoints: 1m
    bls-public-key-list: 1m
    epochs-info: 1m
    epoch-messages: 1m
    current-epoch: 1m
    validators: 1m
    delegators: 1m
    btc-main-chain: 1m
    delegation-lifecycle: 1m
    btc-checkpoints-info: 1m
    btc-checkpoint-params: 1m
    epoching-params: 1m
    raw-checkpoint-list: 1m
    blocks: 5s
    txs: 5s
    cmc: 2h
    finality-providers: 1m
    btc-delegations: 1m
    finality-blocks: 5s
    votes-at-height: 5s
    finality-provider-power: 5s
    btc-delegation-states: 1m
    slashing-evidence: 1m
    btc-staking-params: 1m
    reward-gauges: 1m
btc:
  endpoint: bitcoind-signet.devnet.babylonchain.io:443
  disable-tls: false
  net-params: testnet
  rpc-user: rpcuser
  rpc-pass: rpcpass
metrics:
  host: 0.0.0.0
  server-port: 2112
